### ISSUE TITLE
Support for multiple compartment for discovery feature

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#1020]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The oci provider allows the discovery of resources as described here: https://www.terraform.io/docs/providers/oci/guides/resource_discovery.html

e.g. 

```
terraform-provider-oci -command=export -compartment_name=<name of compartment to export> -output_path=<directory under which to generate Terraform files>
```

However, the command allows exporting resources from only 1 compartment only. For governance/cost reasons, some deployments are done over many compartments. It would therefore be useful if a list of compartments can be accepted by this command instead of just 1 compartment.

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by mulpk** [comment]
@hyder Thank you for your feedback. We will add it to the Resource Discovery Roadmap.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
