### ISSUE TITLE
Service error:NotAuthorizedOrNotFound

### ISSUE THREAD

**Issue by pguerin3** [oracle/terraform-provider-oci#1256]
I can use the console directly, and create an Integration instance to any compartment.

However when I'm running the OCI Integration (\terraform-provider-oci\examples\integration), nothing is created by Terraform.
I get the error in the following log file:
[error.txt](https://github.com/terraform-providers/terraform-provider-oci/files/5738018/error.txt)

I am using a recent version of Terraform.
> terraform -v
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/oci v4.5.0

**Comment by parrneet** [comment]
Hi @pguerin3 Failure is coming from service. Please share the debug log that I can pass on to service team for investigation.
TF_LOG=DEBUG
OCI_GO_SDK_DEBUG=v

**Comment by pguerin3** [comment]
ok - here it is
[error-debug.txt](https://github.com/terraform-providers/terraform-provider-oci/files/5749375/error-debug.txt)

**Comment by srishtipmishra** [comment]
@pguerin3 - Can you please provide the tf config file? The service team needs info on the database name that this backup resource was being created from. Thanks

**Comment by pguerin3** [comment]
I used the default tf config file, and did not modify it.
All variables were entered from the prompt, and were not defined inside the config file.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
