### ISSUE TITLE
Support OCI_CLI_CONFIG_FILE for provider configuratiom

### ISSUE THREAD

**Issue by rbair23** [oracle/terraform-provider-oci#1258]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In my CI/CD configuration I would like to dynamically generate the OCI config file and use OCI_CLI_CONFIG_FILE to refer to it, so that the provider will use that generated config. It appears that the provider only supports ~/.oci/config right now.

**Comment by sanyer** [comment]
Seems like terraform-provider-oci relies on oci-sdk-go mechnism of falling back to filename specified in `OCI_CONFIG_FILE` if `~/.oci/config` wasn't found. But no, it's no possible to use custom config_file path :-(

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.

**Comment by sanyer** [comment]
Oh wow, it's been a while :-D
Thanks for answering @ravinitp 

I'll check again if this was fixed.
