### ISSUE TITLE
Terraform Apply Fails while creating OCI DBaaS 

### ISSUE THREAD

**Issue by bsmahara** [oracle/terraform-provider-oci#1317]
Hi ,

I am getting the below error while running terraform apply for creating a OCI DB instance .

Error : 

Error: Service error:InvalidParameter. Unable to process JSON input. http status code: 400. Opc request id: af354517e6afb06f3ca91777b060b440/BB33865F5B9AE7C114453ADF9C48300C/10D5F714C73EEB97120F8328247EE5F7

  on db.tf line 4, in resource "oci_database_db_system" "test_db_system":
   4: resource "oci_database_db_system" "test_db_system" {

The  db.tf config file is as attached 
[db.tf.zip](https://github.com/terraform-providers/terraform-provider-oci/files/6083075/db.tf.zip)

Please help resolve this issue .

Thanks,
Bhabani

**Comment by bsmahara** [comment]
Terraform version is "Terraform v0.14.7"

**Comment by rashik-bhasin** [comment]
Hi, thanks for the question. We have asked the service team to clarify the behavior. 
Thanks!

**Comment by rashik-bhasin** [comment]
Hi @bsmahara ,
Can you share please provide db system OCID( or tenancy ocid) and region.

**Comment by bsmahara** [comment]
Hi ,
Why do you need the OCI ID of the tenant.


I would need some pointers if the OCI Resource is correct as mentioned in db.tf or is there an update ?

Thanks,
Bhabani

**Comment by bsmahara** [comment]
Hi Team,

Could you please help.

Regards,
Bhabani

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
