### ISSUE TITLE
Update Shape of oci_database_db_system with TF possible?

### ISSUE THREAD

**Issue by pirat8** [oracle/terraform-provider-oci#1354]
(Terraform v0.14.8; oci-pligin: Provider version: 4.22.0, released on 2021-04-14.)

I created a Oracle-DB with oci_database_db_system and shape VM.Standard.2.1 initially. Later I tried tried to update the shape to VM.Standard.2.2 with TF. The process failed.

>snip
Error Message: Internal error occurred 
Suggestion: The service for this resource encountered an error. Please contact support for help with service: Database Db System
>snip

However I could update the shape in Oracle-Console. Is this a missing feature in TF?

Bets regards
Thomas

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
