### ISSUE TITLE
Resource type "oci_load_balancer_load_balancer_routing_policy" is wrongly mentioned in the doc

### ISSUE THREAD

**Issue by vickyvikas7988** [oracle/terraform-provider-oci#1369]
In below terraform document  resource type is wrongly mentioned.

https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/load_balancer_load_balancer_routing_policy

```
The provider provider.oci does not support resource type   
"oci_load_balancer_load_balancer_routing_policy".   

Error: Invalid resource type   
   
  on load_balancer_routing_policy.tf line 21, in resource "oci_load_balancer_load_balancer_routing_policy" "prometheus_load_balancer_routing_policy":   
  21: resource "oci_load_balancer_load_balancer_routing_policy" "prometheus_load_balancer_routing_policy" {   
   
The provider provider.oci does not support resource type   
"oci_load_balancer_load_balancer_routing_policy".   

```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
