### ISSUE TITLE
Add reference to APIs on each resource/data source documentation page?

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Would you consider adding links to relevant API documentation pages on each of the resource/data source pages? I see reference on occasion but generally find myself having to lookup the API pages separately to see definitely required attributes, acceptable input values, capitalization requirements (i.e. some input values are statically upper case and others lower case).

Seems there is a clearly-defined direct correlation of resource/datasource to API so would be very logical to include and low maintenance (i.e. API doc links seem relatively static).

Thank you for considering this.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
