### ISSUE TITLE
Documentation for identity_compartment data source is incorrec

### ISSUE THREAD

**Issue by pastyGRB** [oracle/terraform-provider-oci#1395]
The documentation provided at:
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/data-sources/identity_compartment

It indicates that compartment_id is the required field to execute this data-source.  However, this fails as the terraform code expects id as required argument (not compartment_id).  The data source works as expected, but the documentation is just incorrect.

Thanks

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
