### ISSUE TITLE
Allow bastion service to connect to a list of subnets

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#1440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)
Currently, the bastion service allows connecting to hosts in 1 subnet only:

```
resource "oci_bastion_bastion" "test_bastion" {
    #Required
    bastion_type = var.bastion_bastion_type
    compartment_id = var.compartment_id
    target_subnet_id = oci_core_subnet.test_subnet.id
}
```
If users need to connect to hosts in different subnets, they will then need to create multiple bastions. This is inefficient and harder to manage and audit.

### Potential Terraform Configuration

It would be preferable to give users the possibility of submitting a list of subnet ids instead:
```hcl

resource "oci_bastion_bastion" "test_bastion" {
    #Required
    bastion_type = var.bastion_bastion_type
    compartment_id = var.compartment_id
    target_subnet_ids = ["ocid1.subnet....","ocid1.subnet.."]
}
```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
