### ISSUE TITLE
Change the shape of a DBaaS server

### ISSUE THREAD

**Issue by revchris** [oracle/terraform-provider-oci#1444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
0.13.7

### Affected Resource(s)
oci_database_db_system

### Terraform Configuration Files
Simply changing the "shape" option from "VM.Standard2.2" to "VM.Standard2.4"

### Expected Behavior
Terraform updates to the new shape, the way it is done in through the console.

### Actual Behavior
Terraform destroyed and then created the new DB server with the new shape

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
