### ISSUE TITLE
Service: Core Vcn  Error Message: Authorization failed or requested resource not found.

### ISSUE THREAD

**Issue by afandiyev** [oracle/terraform-provider-oci#1460]
Hi,

Not able to create VCN using terraform, but from UI Console no problem with the same credentials.

Error: 404-NotAuthorizedOrNotFound
Provider version: 4.47.0, released on 2021-10-06.
Service: Core Vcn
Error Message: Authorization failed or requested resource not found.
OPC request ID: 34275761e7bb28a3890d0550ad2526e7/5499CE9389704413B425E8D21F8B454A/953ADF18881997CD3B5DFFDA115A5894
Suggestion: Either the resource has been deleted or service Core Vcn need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/pol

  on vcn.tf line 1, in resource "oci_core_vcn" "vcn_iad":
   1: resource "oci_core_vcn" "vcn_iad" {

### Provider.tf ###
provider "oci" {
    tenancy_ocid = var.tenancy_ocid
    user_ocid = var.user_ocid
    private_key_path  = var.private_key
    fingerprint = var.fingerprint
    region = var.region_iad
}

### vcn.tf ###
resource "oci_core_vcn" "vcn_iad" {
  cidr_block     = "10.0.0.0/16"
  dns_label      = "vcn_iad"
  compartment_id = "var.compartment_ocid"
  display_name   = "vcn_iad"
}

output "vcn_id_iad" {
  value = "oci_core_vcn.vcn_iad.id"
}

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
