### ISSUE TITLE
shape VM.Standard.E2.2 always gives "update in place" changes ocpu and memory 

### ISSUE THREAD

**Issue by holeunlee** [oracle/terraform-provider-oci#1474]
We have some instances which have been deployed with VM.Standard.E2.2 Shape.

In the latest provider, when running a plan, it states the memory and ocpu wants to change, while NO different shape config is configured. We have tested this multiple times and have learned NO real changes is done on the instance, and thus, ignored it for a while.

This does create confusion, in cases when we have mixed instances configured with FLEX types causing a real update with reboots as effect. It is hard to differentiate between tens to hundreds of instances in single plan.

 ~ shape_config {
          ~ memory_in_gbs                 = 16 -> 8
          ~ ocpus                         = 2 -> 1
            # (6 unchanged attributes hidden)

Please take a look into this.

Kind regards,

Holeun Lee

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
