### ISSUE TITLE
Support for burstable E3 Shape 

### ISSUE THREAD

**Issue by AnykeyNL** [oracle/terraform-provider-oci#1508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for E3 Burstable shape.

for node_shape_config please allow extra parameter
baseline_ocpu_utilization = "BASELINE_1_8" or "BASELINE_1_2"

### New or Affected Resource(s)

oci_containerenine_node_pool

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
