### ISSUE TITLE
How to Start/Stop OCI VM using the terraform. I am unable to figure out using couple of arguements but unable to do so 

### ISSUE THREAD

**Issue by Deepak9421** [oracle/terraform-provider-oci#1537]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

Before using this template, check whether your question is already answered in one of the following guides:
* [Frequently Asked Questions](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraform.htm)
* [Troubleshooting](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformtroubleshooting.htm)

If you have a support request related to Oracle Cloud Infrastructure services, please [contact Oracle support](https://docs.cloud.oracle.com/iaas/Content/GSG/Tasks/contactingsupport.htm)

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by hyder** [comment]
There's an argument called `state` and it takes "RUNNING" or "STOPPED" as values. 

To start the VM:

state = "RUNNING" 

To stop the VM:

state = "STOPPED"

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
