### ISSUE TITLE
Resource for attaching instances to managed instance group

### ISSUE THREAD

**Issue by et304383** [oracle/terraform-provider-oci#1542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As per the title, we don't have a resource for attaching instances to the managed instance group.  Seems like a huge oversight!  The API support is there, so I can't see a functional reason not to have this supported.

### New or Affected Resource(s)

`oci_osmanagement_managed_instance_group_attach`

### Potential Terraform Configuration

```hcl
resource "oci_osmanagement_managed_instance_group_attach" "attachment" {
  managed_instance_group_id = var.managed_instance_group_id
  managed_instance_id = var.managed_instance_id
}
```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
