### ISSUE TITLE
v4.67.0 broke compatibility with Terraform v0.11.15?

### ISSUE THREAD

**Issue by tomalok** [oracle/terraform-provider-oci#1549]
```
Error: Error asking for user input: 1 error occurred:
   * provider.oci.us-ashburn-1: Incompatible API version with plugin. Plugin version: 5, Core version: 4
```

Forcing the provider to use version 4.66.0 allowed us to proceed.

There didn't seem to be anything in the release notes that indicated that Terraform v0.11.x was no longer supported.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
