### ISSUE TITLE
AI Vision - wrongly named argument

### ISSUE THREAD

**Issue by nugoncal** [oracle/terraform-provider-oci#1554]
Hi,
according to the [official documentation for oci_ai_vision_model] (https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/ai_vision_model), we’re supposed to have 'namespace' as argument, and I’ve just discovered in your [github example](https://github.com/oracle/terraform-provider-oci/blob/master/examples/aiVision/main.tf) that what the code is expecting is 'namespace_name' …
Can this 'namespace_name' be changed to 'namespace' in the code?
if you agree - 'namespace' looks cleaner, less complicated.
'object' and 'bucket' don’t have an appended _name either.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
