### ISSUE TITLE
oci_kms_vault immediate deletion 

### ISSUE THREAD

**Issue by boris-van-hardeveld** [oracle/terraform-provider-oci#1562]
Hello,

According to the documentation, the deletion of a vault puts it into a pending state for a default of 30 days with a minimum of 7 days. During that time, the deletion can still be reversed. I fully understand the reason for this feature, as it avoids accidental loss of (critical) secrets.

However when it comes to Terraform, this is undesired because a vault in a 'pending deletion' state also prevents the deletion of the containing compartment. The result is an 'Error: During deletion, Terraform expected the resource to reach state(s): DELETED, but the service reported unexpected state: ACTIVE.' during terraform destroy, which cannot be resolved. The Terraform state is stuck.

So, my question is: is there a way to have a vault deleted immediately and permanently by using Terraform? For Terraform to be useful/operate correctly, the creation and deletion of all resources should be instant and symmetrical. Azure has a similar feature on its vaults, but still allows immediate deletion if desired.

Thanks a lot.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
