### ISSUE TITLE
Documentation issue for oci_core_instance / is-consistent-volume-naming-enabled

### ISSUE THREAD

**Issue by guidin360** [oracle/terraform-provider-oci#1564]
Hi!

As per the provider documentation https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance#is_consistent_volume_naming_enabled , the parameter is-consistent-volume-naming-enabled defaults to false, however if i don't set this parameter it's actually set to true, and if i set it to false i get an error:

`Overriding ConsistentVolumeNamingEnabled in LaunchOptions is not supported`

Without setting this parameter the vm is created with these settings:

```
"launch-options": {
        "boot-volume-type": "PARAVIRTUALIZED",
        "firmware": "UEFI_64",
        **"is-consistent-volume-naming-enabled": true,**
        "is-pv-encryption-in-transit-enabled": true,
        "network-type": "PARAVIRTUALIZED",
        "remote-data-volume-type": "PARAVIRTUALIZED"
      },
```

Is this expected?

Thanks!

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
