### ISSUE TITLE
Support for nested_json in oci_logging_unified_agent_configuration

### ISSUE THREAD

**Issue by trondstromme** [oracle/terraform-provider-oci#1571]
Hi.
I've been trying to parse audit log output from Hashicorp Vault
(see examples on https://support.hashicorp.com/hc/en-us/articles/360000995548-Audit-and-Operational-Log-Details)
Initially I though this'd be straight forward using the JSON parser type.
However the audit log output uses nested JSON.
In the OCI console there's an option if you hand craft a parser to select "simple" or "nested" json and in the latter case of specifying a separator.

Are there plans to support the nested json type in oci_logging_unified_agent_configuration any time soon?

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
