### ISSUE TITLE
Add lifecycle Meta-Argument code or Argument reference description part of oci_core_instance_configuration documentation

### ISSUE THREAD

**Issue by Rohitmalakar1999** [oracle/terraform-provider-oci#1574]
Hi Team,

I was working on oci_core_instance_configuration ( Already attached with instance pool ) userdata/image update but facing an issue while terraform apply as terraform try to destroy existing instance configuration and update new instance configuration on instance pool but it does not work as existing terraform is already attached to instance pool.

I was looking for a solution and did not find anything on oci oci_core_instance_configuration docs. Then looked at aws launch configuration docs and similar to that tried lifecycle Meta-Argument mentioned below with my code and it worked.

  lifecycle {
    create_before_destroy = true
  }

Kindly update oci oci_core_instance_configuration docs and add Argument reference for ifecycle Meta-Argument or update sample code with lifecycle Meta-Argument to let the user know it is supported.

Thanks,
Rohit Malakar

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
