### ISSUE TITLE
provider alias source still pointing to hashicorp/oci

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

terraform: v1.2.2
oracle/oci: 4.78.0

### Affected Resource(s)

ALL. Issue is with the provider source defined as "oracle/oci" mismatching with provider alias always from "hashicorp/oci"

### Terraform Configuration Files

```hcl
provider.tf
terraform {
  required_version = "~> 1.2.2"

  required_providers {
    oci = {
      source                = "oracle/oci"
      version               = "~> 4.78.0"
      configuration_aliases = [oci.home]
    }
  }
}

module.tf example

provider "oci" {
  alias  = "home"
  region = var.region
}

module "lz_top_compartment" {
  count     = var.extend_landing_zone_to_new_region == false && var.use_enclosing_compartment == true && var.existing_enclosing_compartment_ocid == null ? 1 : 0
  source    = "../modules/iam/iam-compartment"
  providers = { oci.home = oci.home }
  compartments = {
    (local.enclosing_compartment.key) = {
      parent_id     = var.tenancy_ocid
      name          = local.enclosing_compartment.name
      description   = "Landing Zone enclosing compartment, enclosing all Landing Zone compartments."
      enable_delete = local.enable_cmp_delete
      defined_tags  = local.compartments_defined_tags
      freeform_tags = local.compartments_freeform_tags
    }
  }
}

full code is here: https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/config
```

### Expected Behavior

should be able to use terraform 1.x format to set the provider and provider alias

### Actual Behavior

Error: Provider type mismatch
│ 
│   on iam_compartments.tf line 74, in module "lz_top_compartment":
│   74:   providers = { oci.home = oci.home }
│ 
│ The local name "oci.home" in the root module represents provider
│ "oracle/oci", but "oci.home" in module.lz_top_compartment represents
│ "hashicorp/oci".
│ 
│ Each provider has its own distinct configuration schema and provider types,
│ so this module's "oci.home" can be assigned only a configuration for
│ hashicorp/oci, which is not required by module.lz_top_compartment.

### Steps to Reproduce

1. `terraform init`

**Comment by NagendraNigade** [comment]
Hi, Please find the below response from the Hashicorp. We will need the additional logs if it doesn't work as mentioned below - 

Thanks for reaching out. From the GitHub issue you shared, it looks like the error only shows if you use the configuration_aliases feature introduced in Terraform 0.15.0.

My advice pending the time the provider maintainers fix the issue, is to use the old provider alias format, i.e specifying something like this (below) for the default provider and the aliased ones:

```
# The default provider configuration; resources that begin with `oci_` will use
# it as the default, and it can be referenced as `oci`.
provider "oci" {
  region = "us-east-1"
}

# Additional provider configuration for west coast region; resources can
# reference this as `oci.west`.
provider "oci" {
  alias  = "west"
  region = "us-west-2"
}
```

You can find more information about this here: https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations, however, please inform your customers to avoid using the configuration_aliases feature for now.

If that does not work, please share the customer's full config and trace log for review and further investigation. Please note that I won't be able to reproduce this issue since we don't have access to an Oracle cloud account - since you're a 3rd party provider. Thanks in advance for your understanding.

To get the TRACE log, please type this in your terminal, replacing apply with the terraform command that produced the error:

`TF_LOG=TRACE terraform apply -no-color 2>&1 | tee 75669-apply-trace.log`

and share the generated 75669-apply-trace.log on this ticket. For getting the trace log on Windows & Terraform Cloud/Enterprise, please see https://support.hashicorp.com/hc/en-us/articles/360001113727

Thank you.

**Comment by luckeyca** [comment]
@NagendraNigade I just reported another more serious api key authentication issue which seems to be related to this as well
https://github.com/oracle/terraform-provider-oci/issues/1636

basically if ALL the 3 conditions below are met, api key authentication fails.

1. provider source is set to oracle/oci
2. use module source in the code, instead of the straight resources. ( module "module_name" { ....}}
3. use encrypted api key with password.

**Comment by luckeyca** [comment]
@NagendraNigade looks like another workaround is to stick to the old provider source name hashicorp/oci just like aws/gcp/azure. as far as I can see, the name change from hashicorp/oci to oracle/oci has provided no benefit to users, except for troubles

**Comment by NagendraNigade** [comment]
Tracked under - https://github.com/oracle/terraform-provider-oci/issues/1636
Usable of modules inside terraform currently leading to multiple providers being downloaded.
Best solution is to stick to "hashicorp/oci" source to avoid multiple providers being downloaded.

**Comment by streamnsight** [comment]
Using tf 1.2 here and the problem still exists.
If I only declare the hashicorp/oci provider, both are still being installed.

**Comment by dkooll** [comment]
why this is closed? I simply want to change the namespace and it simply doesn't work...

the old reference hashicorp/oci is still popping up

i would expect that this provider would give migration paths that work

**Comment by wellwanger** [comment]
Hi @luckeyca. I faced similiar issue but in my case the issue was related to versions.tf file not being correctly found locally since I was using a Windows machine and target path used is ../../versions.tf.  Running it a Linux environment and correctly setup required providers and module providers meta-data it works.

**Comment by rinkooy** [comment]
I am also facing same issue , like below :

on provider.tf line 32, in terraform:
  32:   experiments = [module_variable_optional_attrs]
Experimental features are subject to breaking changes in future minor or
patch releases, based on feedback.
If you have feedback on the design of this feature, please open a GitHub
issue to discuss it.
(and 24 more similar warnings elsewhere)
Error: Provider type mismatch
  on main-oke.tf line 55, in module "operator_instance" 
  55:     oci.block_volumes_replication_region = oci.block_volumes_replication_region
The local name "oci.block_volumes_replication_region" in the root module
represents provider "hashicorp/oci", but
oci.block_volumes_replication_region in module.operator_instance represents
oracle/oci.
Each provider has its own distinct configuration schema and provider types,
so this module's "oci.block_volumes_replication_region" can be assigned only
a configuration for oracle/oci, which is not required by
module.operator_instance.
Error: Provider type mismatch
  on vaults_keys.tf line 26, in module "lz_vaults_keys" 
  26:     oci.home = oci.home
The local name "oci.home" in the root module represents provider
hashicorp/oci", but ""oci.home" in module.lz_vaults_keys represents
oracle/oci.
Each provider has its own distinct configuration schema and provider types,
so this module's "oci.home" can be assigned only a configuration for
oracle/oci, which is not required by module.lz_vaults_keys.
Error: Optional object type attributes are experimental
  on .terraform/modules/lz_cloud_guard/cloud-guard/variables.tf line 4:
   4: variable "cloud_guard_configuration" {
This feature is currently an opt-in experiment, subject to change in future
releases based on feedback.
Activate the feature for this module by adding module_variable_optional_attrs
to the list of active experiments

**Comment by joelp172** [comment]
I am also facing this issue. When using a module that contains a sub module, the sub module uses the `hashicorp/oci` provider. Why is this?
