### ISSUE TITLE
Upload to object storage ?

### ISSUE THREAD

**Issue by VAdamec** [oracle/terraform-provider-oci#225]
So I can create bucket, preauth request, but unable to upload files. Are there any plans to support object upload ? I can use local exec, but it will be perfect to have resource for such operation (with etag, last-modified support).

My actual solution (work only for first run, next runs ignore token creation and consul KV content)

```
resource "baremetal_objectstorage_preauthrequest" "writableObject" {
  namespace = "${var.namespace_name}"
  bucket = "${baremetal_objectstorage_bucket.t_private.name}"
  object = "cloud-instance.cfg"
  name = "DevOps-CloudInit-Upload"
  access_type = "ObjectReadWrite"
  time_expires = "2017-08-14T23:00:00Z"

  provisioner "local-exec" {
      command = "curl -XPUT 'https://objectstorage.us-phoenix-1.oraclecloud.com${baremetal_objectstorage_preauthrequest.writableObject.access_uri}' --data-binary '@templates/cloud-instance.cfg'"
    }

}

resource "consul_key_prefix" "cloudinit" {
  path_prefix = "obmc/terraform/cloudinit/"

  subkeys = {
    "objectpath"         = "https://objectstorage.us-phoenix-1.oraclecloud.com${baremetal_objectstorage_preauthrequest.parOnObject.access_uri}",
  }
  lifecycle "forever" {
    ignore_changes = ["subkeys.objectpath"]
  }
}
```

**Comment by codycushing** [comment]
Have a look at the test for usage: https://github.com/oracle/terraform-provider-oci/blob/master/resource_obmcs_objectstorage_object_test.go#L52

We will add an example with the terraform "file" helper shortly, but there are limitations to the size of objects you can work with since they get stringified and stored in the statefile. Will need a better solution form terraform to support arbitrarily large files.
