### ISSUE TITLE
oci_identity_availability_domains returning ADs out of expected order

### ISSUE THREAD

**Issue by jlamillan** [oracle/terraform-provider-oci#328]
### Terraform Version

<details>
Terraform v0.10.7
</details>

### OCI Provider Version

<details>
terraform-provider-oci 2.0.2
</details>

### Description:
oci_identity_availability_domains is seemingly returning ADs out of _expected_ order. 
Looking through the docs, I don't see that there is any contract that oci_identity_availability_domains return ADs in a specific order, but based on example code, people seem to be interpreting it that way. And as far as I remember, it used to work as expected.

In the example below, the returned list is:

data.oci_identity_availability_domains.ADs.availability_domains[0] ==> PHX-AD-2
data.oci_identity_availability_domains.ADs.availability_domains[1] ==> PHX-AD-1
data.oci_identity_availability_domains.ADs.availability_domains[2] ==> PHX-AD-3

Seems to apply to Ashburn as well.

### Terraform File

```
provider "oci" {
  tenancy_ocid         = "${var.tenancy_ocid}"
  user_ocid            = "${var.user_ocid}"
  fingerprint          = "${var.fingerprint}"
  private_key_path     = "${var.private_key_path}"
  region               = "${var.region}"
}

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}

variable "region" {
  default = "us-phoenix-1"
}

data "oci_identity_availability_domains" "ADs" {
  compartment_id = "${var.tenancy_ocid}"
}

resource "null_resource" "echo-ad1" {
  provisioner "local-exec" {
    command = <<LOCAL_EXEC
echo ${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}
LOCAL_EXEC
  }
}

resource "null_resource" "echo-ad2" {
  provisioner "local-exec" {
    command = <<LOCAL_EXEC
echo ${lookup(data.oci_identity_availability_domains.ADs.availability_domains[1],"name")}
LOCAL_EXEC
  }
}

resource "null_resource" "echo-ad3" {
  provisioner "local-exec" {
    command = <<LOCAL_EXEC
echo ${lookup(data.oci_identity_availability_domains.ADs.availability_domains[2],"name")}
LOCAL_EXEC
  }
}
```

### Terraform Apply

```
data.oci_identity_availability_domains.ADs: Refreshing state...
null_resource.echo-ad1: Creating...
null_resource.echo-ad2: Creating...
null_resource.echo-ad3: Creating...
null_resource.echo-ad1: Provisioning with 'local-exec'...
null_resource.echo-ad2: Provisioning with 'local-exec'...
null_resource.echo-ad3: Provisioning with 'local-exec'...
null_resource.echo-ad3 (local-exec): Executing: ["/bin/sh" "-c" "echo hXgQ:PHX-AD-3\n"]
null_resource.echo-ad1 (local-exec): Executing: ["/bin/sh" "-c" "echo hXgQ:PHX-AD-2\n"]
null_resource.echo-ad2 (local-exec): Executing: ["/bin/sh" "-c" "echo hXgQ:PHX-AD-1\n"]
null_resource.echo-ad2 (local-exec): hXgQ:PHX-AD-1
null_resource.echo-ad2: Creation complete after 0s (ID: 7543711477911731136)
null_resource.echo-ad1 (local-exec): hXgQ:PHX-AD-2
null_resource.echo-ad1: Creation complete after 0s (ID: 3504201122002210711)
null_resource.echo-ad3 (local-exec): hXgQ:PHX-AD-3
null_resource.echo-ad3: Creation complete after 0s (ID: 3285746276885397138)

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

**Comment by RiaanRossouw** [comment]
As of this morning I have the same problem.  Yesterday a terraform plan was fine with no changes.  This morning ALL subnets want to be destroyed and therefore ALL instances.

Example:
-/+ oci_core_subnet.Production-priv01-AD1 (new resource required)
      id:                           "ocid1.subnet.oc1.iad.aaaaaaaawhnbmajiaajejaztyfoy6sgg5llozcfxqmpcaodsbxltabclitsa" => <computed> (forces new resource)
      availability_domain:          "BDQS:US-ASHBURN-AD-1" => "BDQS:US-ASHBURN-AD-2" (forces new resource)

**Comment by darkfibre** [comment]
Seeing the same issue here.

availability_domains[0] -> "oPfG:PHX-AD-2"
availability_domains[1] -> "oPfG:PHX-AD-1"
availability_domains[2] -> "oPfG:PHX-AD-3"

**Comment by briangustafson** [comment]
We're looking into this now. Thanks for reporting - I'm seeing this issue as well.

**Comment by briangustafson** [comment]
This has been identified as a service change, which is currently being rolled back in order to restore the original AD order. I'll update this ticket as that progresses. In the meantime, it would be advisable to not apply any production configurations. Just as a config run before the change would try to recreate AD-based resources after, a config run now may try to re-create AD-based resources after the rollback.

**Comment by rahulviswam17** [comment]
@briangustafson : Does this issue exists in "terraform-provider-oci 2.0.1" as well ? Please confirm.

**Comment by briangustafson** [comment]
@rahulviswam17 This is a service issue, and applies to all provider versions.

**Comment by rahulviswam17** [comment]
@briangustafson : Thank you , I'll wait for the update to make any further network change as advised.

**Comment by briangustafson** [comment]
The service is back to returning the previous AD ordering in all regions, so this issue should be resolved.

I'll leave this ticket open for a bit just for visibility. Please let us know if there are any further issues.

**Comment by RiaanRossouw** [comment]
Looks good in my case.

No changes. Infrastructure is up-to-date.

**Comment by jlamillan** [comment]
Looks good to me as well.

**Comment by LorenzKeller** [comment]
believe to know, facing the same error, again.
Last Time, datacenter Frankfurt went live.
Today DC Toronto went live ... 
--
./terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.oci_identity_availability_domains.ADs: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.oci_identity_availability_domains.ADs: 1 error(s) occurred:

* data.oci_identity_availability_domains.ADs: data.oci_identity_availability_domains.ADs: Get https://identity.eu-frankfurt-1.oraclecloud.com/20160918/availabilityDomains?compartmentId=ocid1.tenancy.oc1 ...
: dial tcp: i/o timeout

**Comment by briangustafson** [comment]
Hi @LorenzKeller  - Could you clarify exactly what you are seeing?

**Comment by LorenzKeller** [comment]
Dear,
scripts where fine till Friday noon. Since then I receive the above error, when running terraform plan.
Not sure, but last Friday the datacenter in Toronto went live. Since then, scripts are returning error on refreshing data.oci_identity_availability_domains.ADs.
I saw this post with the error end of October 2017, just the time, when the DC in Frankfurt went live.
Anyway.
Error: 
./terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.oci_identity_availability_domains.ADs: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

data.oci_identity_availability_domains.ADs: 1 error(s) occurred:

data.oci_identity_availability_domains.ADs: data.oci_identity_availability_domains.ADs: Get https://identity.eu-frankfurt-1.oraclecloud.com/20160918/availabilityDomains?compartmentId=ocid1.tenancy.oc1 ...
: dial tcp: i/o timeout
 
$ ./terraform version
Terraform v0.11.11
+ provider.oci v3.5.0

Any idea?
Kind regards
Lorenz

**Comment by rramge** [comment]
Hi Lorenz,

I had this problem last week, but it turned out to be a local problem with my VirtualBox 6.0. Always happened during resource refreshing until I shut the VM down and relaunched it. Especially after I noticed that using terraform from other clients didn’t have this issue.

So, if you can feel that terraform is really taking a break before throwing this error, I recommend giving it as try from another client, as well as checking the connectivity and proxy settings if you are on-prem at a customer’s site. I am pretty sure this is a local issue, and would also happen with a different provider at this time.

Ralf

**Comment by rramge** [comment]
Hi again,

I ran into a problem with possibly the same effect Lorenz Keller experienced.

I am currently trying to manage multiple OCI regions with a single terraform setup, and I see a lot of timeouts during refreshing.
My uneducated guess at this point is that it might be connected to my attempt of invoking multiple oci providers in parallel.

I see that during the initial refreshing phase of a “terraform plan” or “terraform apply”, the refreshing seems to run into timeouts, randomly. It finishes eventually, but once the refresh gets stuck, it can take several minutes until terraform continues.

The timeouts disappear once I remove the additional provider blocks and work in my home region only.

Lorenz, my question: Do you also work with multiple regions or maybe multi-cloud configurations?

My setup:

--- 8< ---
module "eu-frankfurt-1" {
        source = "regions/eu-frankfurt-1/"
        tenancy_ocid = "${var.tenancy_ocid}"
        user_ocid = "${var.user_ocid}"
        fingerprint = "${var.fingerprint}"
        private_key_path = "${var.private_key_path}"
        region = "eu-frankfurt-1"
}

module "uk-london-1" {
        source = "regions/uk-london-1/"
        tenancy_ocid = "${var.tenancy_ocid}"
        user_ocid = "${var.user_ocid}"
        fingerprint = "${var.fingerprint}"
        private_key_path = "${var.private_key_path}"
        region = "uk-london-1"
}
--- 8< ---

And each module directory contains a copy of the usual provider block (which also exists in the root terraform directory, because of the global components like compartments):

--- 8< ---
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}

provider "oci" {
  version          = ">= 3.13.0"
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region           = "${var.region}"
}
--- 8< ---

If anyone has an idea, let me know 😊

Cheers,

Ralf

From: Ralf Ramge
Sent: Monday, January 21, 2019 9:52 AM
To: 'terraform-providers/terraform-provider-oci' <reply@reply.github.com>
Subject: RE: [terraform-providers/terraform-provider-oci] oci_identity_availability_domains returning ADs out of expected order (#328)

Hi Lorenz,

I had this problem last week, but it turned out to be a local problem with my VirtualBox 6.0. Always happened during resource refreshing until I shut the VM down and relaunched it. Especially after I noticed that using terraform from other clients didn’t have this issue.

So, if you can feel that terraform is really taking a break before throwing this error, I recommend giving it as try from another client, as well as checking the connectivity and proxy settings if you are on-prem at a customer’s site. I am pretty sure this is a local issue, and would also happen with a different provider at this time.

Ralf

**Comment by abhilash-av** [comment]
Hello
I think it is better if we start a new Github issue for discussing this in more detail. However, to close the loop here; if you want to share your Terraform Config files to create resources for multiple environments or regions, you will need repeat the below steps for every environment (prod, stage, test, dev) and/or region by following the commands like (following the best practice of encoding the tenancy name in the state file)
`terraform plan -state=terraform.tfstate.<tenancy_name>.$TF_VAR_env.<region>`
`terraform apply -state=terraform.tfstate.<tenancy_name>.$TF_VAR_env.<region>`

Happy to answer any other questions that you may have as a separate Github issue!
