### ISSUE TITLE
policy format change in API? causes terraform to rebuild policies

### ISSUE THREAD

**Issue by PeterJamesHarrison** [oracle/terraform-provider-oci#371]
Issues #230 has occurred again.  
To give you a few examples:

statements.0:  
"allow group GIT-Sys-Admins to manage instance-family in tenancy where all {target.compartment.name = /GIT-*/, target.compartment.name ! = /GIT-RMSS-*/}" => 
"allow group GIT-Sys-Admins to manage instance-family in tenancy  where all { target.compartment.name=/GIT-*/ , target.compartment.name!=/GIT-RMSS-*/ }"
statements.1: 
"allow group GIT-Network-Admins to manage load-balancers in tenancy where target.compartment.name = /GIT-*/" => 
"allow group GIT-Network-Admins to manage load-balancers in tenancy  where target.compartment.name = /GIT-*/"
statements.2: 
"allow group GIT-Network-Admins to manage instance-family in compartment GIT-Networks" => 
"allow group GIT-Network-Admins to manage instance-family in compartment git-networks"

As you can see the spaces have been removed from the regular expressions.  Also, the space has been removed between the tenancy and where.   And finally the compartment names are being forced to lowercase.  

It looks like they have fixed the first two issues that was previously introduced, but have added the “to_lower” on the compartment names.

**Comment by codycushing** [comment]
Hello, can you please provide your Terraform version and OCI provider version. Also, your repro steps are also not stated and we need more information about your scenario. Are you also adding or removing a statement when you are observing deltas in other statements? Have you made a change to the statements outside of terraform? Or is this purely running plan after a recent, previously successful apply with no .tf file changes?

The fix for this endpoint reformatting policy statements was to only compare etags. Any intervening change to the resource would change the etag and result in a new diff against existing policy statements.

**Comment by PeterJamesHarrison** [comment]
I am using 
Terraform v0.11.0
terraform-provider-oci v2.0.2

All I was doing was adding one addition policy statement.  However, it required all other policies that didn't match the current format to require a rebuild.  This is exactly the same thing that happened with Issue #230 

This was the only real change I was attempting.
  ~ oci_identity_policy.GIT-Read-Only
      statements.#:  "2" => "1"
      statements.1:  "allow group GIT-Read-Only to read audit-events in tenancy" => ""

If you like I can send you the TF code and the terraform plan output offline

**Comment by codycushing** [comment]
This is currently unavoidable. Any time you are actually making a change to the policy, the etag will change and any previously suppressed diff indications from statement to statement will then no longer be suppressed. 

Behind the scenes the policy api treats all statements as one blob though, which means any update to the statements set is really replacing the entire previous set (this occurs at the server), so you shouldn't need to worry if previously saved statements now appear different.

It is confusing and we are thinking through possible solutions, but because it is not actually harmful, it is probably better in the short term to reformat the statements how the server indicates.

**Comment by PeterJamesHarrison** [comment]
Thanks for the details.  I will close the issue
