### ISSUE TITLE
Use PrivateIP while creating OCI instance

### ISSUE THREAD

**Issue by kdvlr** [oracle/terraform-provider-oci#378]
It looks like "private_ip" is currently a computed field. While creating an instance from the console, we can set a Private IP. 

When will this capability be added to the OCI provider ?

**Comment by briangustafson** [comment]
You can set this in the oci_core_instance resource today using the private_ip field inside of create_vnic_details. See https://github.com/oracle/terraform-provider-oci/blob/master/docs/resources/core/instance.md. It is pretty confusing, since there is also a private_ip field at the root level in the instance resource which cannot be set.

**Comment by briangustafson** [comment]
The docs have been updated to help clarify this, see #396. Closing.
