### ISSUE TITLE
rhel74_image - should echo output of scripts to disk

### ISSUE THREAD

**Issue by goltermann** [oracle/terraform-provider-oci#382]
If ipxe.sh hits some error and hangs up (which could be a poorly specified, it's hard to debug.

We should echo to output of that script to the ~/ of the ipxe instance.  We should do the same for sacrifice-launch.sh.

**Comment by nelsonse** [comment]
Here is the problem with ipxe.sh...since this is executed as part of the user_data portion of cloud-init, there is no way that I am aware of to capture the output of the script during execution.  However, I believe the output of user-data is captured in /var/log/cloud-init-output.log.  I will see if I can output any additional information, but I am dealing with a lack of space (32k bytes) as a maximum size of cloud-init at this point, so adding anything extra required taking away.  I will update this thread as I find items.

**Comment by anandhmahal** [comment]
@nelsonse - any update on this thread? Were you able to find how the information can be exposed?
@goltermann - are you still waiting on this?

**Comment by alexng-canuck** [comment]
We're in the middle of moving all the solutions from this repo over to https://github.com/oracle/terraform-examples/tree/master/examples/oci

This issue can now be tracked here: oracle/terraform-examples#21

Closing this one.
