### ISSUE TITLE
rhel74-images - Need clearer examples in configuration.tf

### ISSUE THREAD

**Issue by goltermann** [oracle/terraform-provider-oci#383]
When running through an example, I got caught up a few times on putting in bad data.  We should make the build_env examples easier:

1) Compartment - you cannot use the root compartment, make that clear
2) AD - you need to specify the AD as "AD-N" without any other prefix or suffix
3) Subnet - the subnet cannot contain a space - that's an issue, because if you create a VCN via the UI and have it automatically create subnets, it will create them of the form "Public Subnet xXXx:REGION-AD"

**Comment by goltermann** [comment]
Also of note, the subnet needs to allow ping to work - so the security list should have ICMP All on the 10.0.0.0/16 subnet.

**Comment by nelsonse** [comment]
In addtion, subnet also needs port 80 open as well.

**Comment by briangustafson** [comment]
The subnet/security list configuration issues could be fixed by creating them through TF rather than using data sources.

**Comment by nelsonse** [comment]
The subnet/security list cannot be automated at this time since there is no way to update security lists in TF currently.  Once that functionality is available, the security list for the subnet can be updated with the appropriate rules.

Requirements for security lists are being updated in the README.

I cannot repo the "space in the subnet" issue.

**Comment by alexng-canuck** [comment]
We're in the middle of moving all the solutions from this repo over to https://github.com/oracle/terraform-examples/tree/master/examples/oci

This issue can now be tracked here: oracle/terraform-examples#22

Closing this one.
