### ISSUE TITLE
invalid OCID provided for import hangs instead of producing error

### ISSUE THREAD

**Issue by nshttpd** [oracle/terraform-provider-oci#415]
### Terraform Version

```
Terraform v0.11.1
  + provider.oci v2.0.6
```

### Description:

importing an `oci_identity_policy` while providing the incorrect OCID (like, say a container ocid and not a policy ocid, because things) causes the import process to just hang and not error out. In fact it hangs saying that it was successful.

```
2018-01-09T13:10:27.272-0500 [DEBUG] plugin.terraform-provider-oci_v2.0.6: 2018/01/09 13:10:27 [INFO] terraform-provider-oci 2.0.6
2018-01-09T13:10:27.273-0500 [DEBUG] plugin.terraform-provider-oci_v2.0.6: 2018/01/09 13:10:27 [DEBUG] plugin: plugin address: unix /var/folders/2f/ppyk_7p17xxc12s6s8d24f9h0000gn/T/plugin754887660
oci_identity_policy.elk_compartment: Importing from ID "ocid1.compartment.oc1..aablahblahblahkhdpa"...
oci_identity_policy.elk_compartment: Import complete!
  Imported oci_identity_policy (ID: ocid1.compartment.oc1..aaabblablahblahgkhdpa)
oci_identity_policy.elk_compartment: Refreshing state... (ID: ocid1.compartment.oc1..aablahblahblahhdpa)
```

Notice it's not an ocid1.policy, but ocid1.compartment so it should at some point have produced an error trying to serialize the REST response into the TF Object Schema.

**Comment by alexng-canuck** [comment]
I was able to see this as well. Though it appears to be hanging, what's actually happening is the identity service is returning us a 404 error since the import ID can't be found. The SDK used by the terraform provider continues to retry this request for long period of time (10 minutes) and should fail afterwards.

There are a few things that need further investigation here:
1) Why we get an "Import complete!" message, which is misleading.
2) Whether we should have some sort of message that is logged when retrying, to avoid the appearance of a hang.
3) Whether this retry period needs to be shortened especially since 404 errors are rarely intermittent errors.

**Comment by alexng-canuck** [comment]
Created an internal issue to investigate how to improve the experience for retries. Otherwise, this is not an actual hang, since the operation will eventually fail after 10 minutes.

**Comment by nshttpd** [comment]
As an additional note, I'm having the "hang" again where backends in a backend_set  have been removed via the UI, and a `terraform refresh` just sits while getting the data. I'm assuming (since I don't have it in debug logging mode) that it's getting 404's asking the API for these objects and will sit and retry for 10 minutes.

**Comment by kohashim** [comment]
FYI, there is an option "disable_auto_retries" in the "oci" provider.  Be careful though to disable it because it would affect every operation when applying your terraform config.

We have a backlog item for making the retry behavior configurable.

Closing for now since this is not an actual issue.  Feel free to reopen if necessary.  Thanks.
