### ISSUE TITLE
Updating LB Certificate  does not force backend sets/Listeners to Regenerate

### ISSUE THREAD

**Issue by tjkervin** [oracle/terraform-provider-oci#448]
### Terraform Version

<details>
# Run this command to get the terraform version:

Terraform v0.11.2

</details>

### OCI Provider Version

<details>
v2.0.5
</details>

### Description:
When updating the certificate details, it forces the certificate to be rebuilt. This does not trigger the listeners or backend sets to regenerate, which causes an error on the apply. See relevant error below

### Terraform Apply

<details>
Error: Error applying plan:

1 error(s) occurred:

* oci_load_balancer_certificate.lb_spmboem-cert1 (destroy): 1 error(s) occurred:

* oci_load_balancer_certificate.lb_spmboem-cert1: unexpected state 'FAILED', wanted target 'SUCCEEDED_WORK_REQUEST, SUCCEEDED'. last error: %!s(<nil>)

</details>

### Works Status in OCI Console

<details>
Error Details: Listener for 'lb_spmboem_lsnr_7102' refers to unknown certificate 'spmboem'
</details>

**Comment by tjkervin** [comment]
Workaround is to taint the resources that reference the certificate, but this should be handled by the terraform provider.

**Comment by codycushing** [comment]
Hello, can you please include the relevant (load balancer related) portion of your .tf file(s)?
Thanks

**Comment by tjkervin** [comment]
I can, but this should be pretty simple to reproduce: 

1) Generate an LB with a certificate. Configure backend sets and listeners to use this certificate. 
2) Change the details of the certificate, and execute a terraform plan. Note that it only attempts to regenerate the certificate and not the backend sets or listeners referencing it. 
3) Run the apply to see the error referenced in the issue description.

`resource "oci_load_balancer" "lb_stwmsqa3" {
  shape          = "100Mbps"
  compartment_id = "${var.compartment_ocid}"
  subnet_ids     = [
    "${oci_core_subnet.MB_GLB_LOG_LB_SUB_AD2_DEV.id}"
  ]
  display_name   = "lb_stwmsqa3"
  is_private     = true
}

resource "oci_load_balancer_certificate" "lb_stwmsqa3-cert1" {
  load_balancer_id   = "${oci_load_balancer.lb_stwmsqa3.id}"
  ca_certificate     = "${data.vault_generic_secret.ManhSSL.data["ca_cert"]}"
  certificate_name   = "${data.vault_generic_secret.ManhSSL.data["name"]}"
  private_key        = "${data.vault_generic_secret.ManhSSL.data["private_key"]}"
  public_certificate = "${data.vault_generic_secret.ManhSSL.data["pub_cert"]}"
  passphrase         = "${data.vault_generic_secret.ManhSSL.data["passphrase"]}"
}

resource "oci_load_balancer_backendset" "lb_stwmsqa3_SSH" {
  name             = "lb_stwmsqa3_SSH"
  load_balancer_id = "${oci_load_balancer.lb_stwmsqa3.id}"
  policy           = "ROUND_ROBIN"

  health_checker {
    port     = "12001"
    protocol = "TCP"
    response_body_regex = ".*"
    url_path = "/"
  }
}`

**Comment by alexng-canuck** [comment]
@tjkervin Thanks for the info. This is a bug and it's a consequence of how backend set/listeners are designed to not have explicit references to a unique certificate identifier. Without this explicit dependency, the backend sets/listeners don't know that they need to be regenerated when the certificate changes.

I've shared this feedback with the team and added this to our backlog to investigate how to better handle this.

**Comment by revnav** [comment]
We got the same issue. In fact we have certificates expiration of 2 years and want terraform to handle the cert updates. This issue is preventing us from building simplified process it into our code pipeline. Appreciate any feedback/movement on this.

**Comment by rcohenma** [comment]
I've investigated this issue.
A certificate cannot be deleted if it is attached to another resource (a listener for example).
Because certificate_name in the listener is an updatable parameter, terraform will attempt to recreate the certificate first and then update the listener but the certificate cannot be deleted while it is attached to a listener so it will fail.

You can do the update with the current provider as a 2 step process.
1. Add a new certificate resource to your config and change the listener (and other resources that depend on the certificate you are trying to replace) to point to values in the newly added certificate. Run Apply
2. Remove the old certificate from your config. Run apply

There is a terraform flag that allows you to do  this in 1 step. You will need to add the following inside your certificate  resource
  lifecycle {
    create_before_destroy = true
  }
This will create the new certificate before destroying the old one. HOWEVER you will need to change the name of your certificate when making destructive changes to your certificate resource. Otherwise you will get an error saying that a certificate with that name already exists.

**Comment by codycushing** [comment]
Hello, the documentation has been updated to describe the above work around. Thanks
