### ISSUE TITLE
provider.oci: can not create client, bad configuration: did not find a proper configuration for private key

### ISSUE THREAD

**Issue by markxnelson** [oracle/terraform-provider-oci#467]
### Terraform Version
```
$ terraform -v
Terraform v0.11.3
+ provider.ignition v1.0.0
+ provider.oci (unversioned)
+ provider.random v1.1.0
+ provider.template v1.0.0
+ provider.tls v1.0.1
</details>
```

### OCI Provider Version
```
~/.terraform.d/plugins/terraform-provider-oci
2018/03/07 17:13:30 [INFO] terraform-provider-oci 2.1.0-beta
```

### Description:
I ran `terraform plan` today, without changing anything at all in my code, and I got an error message that private_key_password is required.  That was with 2.0.6 plugin.  I updated to the latest version and I get a slightly different message:  

```
* provider.oci: can not create client, bad configuration: did not find a proper configuration for private key
```

Here is my provider config: 

```
$ cat provider.tf
provider "oci" {
  tenancy_ocid         = "${var.tenancy_ocid}"
  user_ocid            = "${var.user_ocid}"
  fingerprint          = "${var.fingerprint}"
  private_key_path     = "${var.private_key_path}"
  private_key_password = "${var.private_key_password}"
  region               = "${var.region}"
  disable_auto_retries = "${var.disable_auto_retries}"
}
```

### Terraform Plan

I can provide a plan if required.  Have to check if it has any Oracle Confidential information in it first.  I would prefer to provide it by a more secure method please.

**Comment by alexng-canuck** [comment]
Was the error that you got in 2.0.6, something like "private_key_password is required for encrypted private keys"?

This would seem to imply that an encrypted private key was specified in file represented by private_key_path. If so, can you verify that the private_key_password is set to a valid password to decrypt the private key?

Note that the error messages you see has changed slightly between 2.0.6 and 2.1.0 because of different internal logic for getting the private key.

**Comment by markxnelson** [comment]
Yes that was it.  I am going to create a new API key and test again.

**Comment by markxnelson** [comment]
I can confirm that was the issue.  When I created a new API key and provided the password in the tfvars it works fine.
