### ISSUE TITLE
No changes. Infrastructure is up-to-date.

### ISSUE THREAD

**Issue by Gopi1995krishna** [oracle/terraform-provider-oci#498]
Hello Team,
I provisioned an instance in OCI using terraform by using below code,

resource "oci_core_instance" "TFInstance" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
  compartment_id      = "${var.compartment_ocid}"
  display_name        = "TFInstance${random_id.rnd.hex}"
  image               = "${var.InstanceOCID}"
  shape               = "${var.InstanceShape}"
  subnet_id           = "${oci_core_subnet.ExampleSubnet.id}"
  hostname_label      = "tfinstancemachine${random_id.rnd.hex}"
  metadata {
    ssh_authorized_keys = "${var.ssh_public_key}"
//    user_data = "${base64encode(file(var.BootStrapFile))}"
  }
At this stage I am able to login to created instance,
 later there is requirement to execute commands on provisioned instance, so I added below code

resource "oci_core_instance" "TFInstance" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
  compartment_id      = "${var.compartment_ocid}"
  display_name        = "TFInstance${random_id.rnd.hex}"
  image               = "${var.InstanceOCID}"
  shape               = "${var.InstanceShape}"
  subnet_id           = "${oci_core_subnet.ExampleSubnet.id}"
  hostname_label      = "tfinstancemachine${random_id.rnd.hex}"
  metadata {
    ssh_authorized_keys = "${var.ssh_public_key}"
//    user_data = "${base64encode(file(var.BootStrapFile))}"
  }

  connection {
    host           = "${oci_core_instance.TFInstance.public_ip}"
    user           = "${var.os_user["os_user_name"]}"
    type           = "ssh"
    private_key    = "${path.module}/userdata/oempvt_bmcs.ppk"
  }
  provisioner "remote-exec" {
  inline = [
 "yum update -y",
 "yum install -y httpd",
 "mkdir -p /home/opc/softwares",
]
}

Now It was showing  like below output,

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Could you please share what is the issue.

Thanks

**Comment by jbolla** [comment]
I think your configuration needs to tell provisioner to use the connection. The way I've seen that done is that the connection config is nested inside the provisioner. Then your provisioner needs to be set up to work on your instance. It's possible that the fact the connection specifies the host covers that, but it's not a use I'm familiar with. What I've seen before is provisioners nested within the instance resource. Also, by default provisioners run when the resource is created, and since you've run this configuration before that resource is not being created. The only other option is when the resource is destroyed. I think your only solution if you want this to run via terraform is to create a new resource.

Here is an example of using a provisioner (in this case a chef provisioner) on a compute resource with a connection configured: https://github.com/oracle/terraform-provider-oci/blob/master/docs/solutions/chef/compute.tf#L18

**Comment by Gopi1995krishna** [comment]
Hi,
This issue is resolved.
I have done jenkins configuration, how to get login details as output.

Thanks
