### ISSUE TITLE
Allow the provider to report on container engine node provisioning status.

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#564]
### Terraform Version

0.11.7

### OCI Provider Version

2.1.16
</details>

### Description:
Allow the provider to report on container engine node provisioning status. 

<details>
At the moment, the provider just creates the node pool and the hosts in it. We have to check on the status by either looking at the UI console or using kubectl. It would be good if there was a way the provider could also provide a similar capability i.e. not just the compute but whether the the worker nodes have been successfully configured.

This would enable the deployment of Kubernetes resources to the worker nodes when the nodes become active.
</details>

**Comment by srishtipmishra** [comment]
This is now supported as a part of Terraform Provider's 3.69.0 release.

**Comment by srishtipmishra** [comment]
Marking this upstream as service team is working on it.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
