### ISSUE TITLE
resource oci_containerengine_node_pool, attribute initial_node_labels should probably be a map not a list

### ISSUE THREAD

**Issue by rgmccaw** [oracle/terraform-provider-oci#826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`inital_node_labels` is currently a list of maps, each map with the keys "key" and "value". So it's basically a map anyway. And if I want to ignore a specific label I have to use the list index instead of a key which is prone to breaking when other devs make changes to the terraform in the future. So it looks something like this:

```hcl
resource "oci_containerengine_node_pool" "nps" {
  ...

  initial_node_labels {
    key   = "my-label-key"
    value = "my-label-value"
  }

  initial_node_labels {
    key   = "not-ignored-key"
    value = "not-ignored-value"
  }

  lifecycle {
    ignore_changes = [
      initial_node_labels[0]
    ]
  }
```

If `initial_node_labels` is changed to a map it could look like:
```hcl
resource "oci_containerengine_node_pool" "nps" {
  ...

  initial_node_labels = {
    "my-label-key" = "my-label-value",
    "not-ignored-key" = "not-ignored-value"
  }

  lifecycle {
    ignore_changes = [
      initial_node_labels["my-label-key"]
    ]
  }
```
In this situation if a dev in the future adds labels, they don't have to worry about adding them before or after existing labels or updating the index in `ignore_changes`

### New or Affected Resource(s)

resource "oci_containerengine_node_pool"

**Comment by kilokahn** [comment]
This is a very good suggestion @rgmccaw - particularly if some of the initial_node_labels are to be ignored in plan computation. 
However, changing the datatype of the existing field is a breaking change, and hence is not recommended for existing customers. We can introduce an additional field that captures this input in the map form, but would need to still support the list field for backward compatibility. Since our terraform provider closely mimics the API (https://docs.cloud.oracle.com/iaas/api/#/en/containerengine/20180222/datatypes/CreateNodePoolDetails) experiences for the other surfaces (SDK, CLI, and Console), we try to keep the Terraform resource modeling as close to the actual API as possible.
Having said that, if there is additional interest in this feature from the community, please 👍 the original issue, and we can pull it in for consideration again. Thanks!

**Comment by hyder** [comment]
We want to be able to add node labels in https://github.com/oracle-terraform-modules/terraform-oci-oke. This is a great suggestion

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
